services:
  - type: web
    name: backend-service
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    autoDeploy: true
    plan: free

  - type: web
    name: frontend-service
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm start
    autoDeploy: true
    plan: free